### ISSUE TITLE
how to deal with multiline json file

### ISSUE THREAD

**Issue by wanghaisheng** [logstash-plugins/logstash-codec-json#20]
i want to import such file to es
how to deal with file like this

```
{
"time" : {
"start" : 1419621623182,
"stop" : 1419621640826,
"duration" : 17644
},
"testSuites" : [ {
"uid" : "ac7efb112b3b91cc",
"name" : "tests.buylinks",
"title" : "Buylinks",
"time" : {
"start" : 1419621623182,
"stop" : 1419621640826,
"duration" : 17644
},
"statistic" : {
"total" : 3,
"passed" : 0,
"pending" : 0,
"canceled" : 0,
"failed" : 3,
"broken" : 0
},
"description" : null,
"testCases" : [ {
"uid" : "441d1d1dd296fe60",
"name" : "test_buylinks",
"title" : "Test buylinks",
"time" : {
"start" : 1419621623182,
"stop" : 1419621640491,
"duration" : 17309
},
"severity" : "NORMAL",
"status" : "FAILED"
}, {
"uid" : "a88c89b377aca0c9",
"name" : "test_buylinks",
"title" : "Test buylinks",
"time" : {
"start" : 1419621623182,
"stop" : 1419621640634,
"duration" : 17452
},
"severity" : "NORMAL",
"status" : "FAILED"
}, {
"uid" : "32c3f8b52386c85c",
"name" : "test_buylinks",
"title" : "Test buylinks",
"time" : {
"start" : 1419621623185,
"stop" : 1419621640826,
"duration" : 17641
},
"severity" : "NORMAL",
"status" : "FAILED"
} ]
} ]
}
```

**Comment by naisanza** [comment]
I'm having the same issue. My first guess will be to use the [multiline filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-multiline.html), however it doesn't make sense to, because the input is JSON and validates as JSON, so just using the JSON codec should be enough.

Though, it seems that the file input codec for JSON doesn't work with multiline JSON

**Comment by naisanza** [comment]
The same issue that I ran into when importing the same JSON file into MongoDB was having to use the `--jsonArray` flag, because the expected input format was `{..},{..}`

So running a script through the json file and removing all EOL characters might work.

**Comment by wanghaisheng** [comment]
thx  i will try

**Comment by naisanza** [comment]
@wanghaisheng you should keep it open! It's a perfect example of different ways the JSON format is being given to Logstash; and they should all work. This could be a bug or feature request
