### ISSUE TITLE
Feature Request: support for "target" option

### ISSUE THREAD

**Issue by bviswana101** [logstash-plugins/logstash-codec-json#24]
JSON fields decoded from message are written to root event. Support for target similar to JSON filter would help avoid namespace clashes.

**Comment by micoq** [comment]
+1
Some plugins like [logstash-input-http_poller](https://github.com/logstash-plugins/logstash-input-http_poller) already have a `target` option but the codec would be a better place.

**Comment by jsvd** [comment]
this was done by @kares at https://github.com/logstash-plugins/logstash-codec-json/pull/37
