### ISSUE TITLE
5.0.0-alpha1 _jsonparsefailure for valid JSON file

### ISSUE THREAD

**Issue by naisanza** [logstash-plugins/logstash-codec-json#26]
Versions:

```
logstash 5.0.0-alpha1
Elasticsearch 5.0.0-alpha1
jre1.8.0_77
```

JSON sample entry

```
[
  {
    "MD5":"85846678ad4dbff608f2e51bb0589a16",
    "MIME-TYPE":"application/octet-stream",
    "FILE TYPE":"Mach-O 64-bit x86_64 executable",
    "ANALYSIS DATE ":"Apr. 9, 2016, 6:34 am",
    "SIZE":"141732",
    "SOURCE":"VirusTotal"
  }
]
```

Logstash JSON parse failure:

```
JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: incompatible json object type=java.lang.String , only hash map or arrays are suppoted>, :data=>"    \"ANALYSIS DATE\":\"Apr. 9, 2016, 6:34 am\"\r", :level=>:error}
```

Logstash conf:

```
input {
        file {
                start_position => "beginning"
                path => "/home/logstash/data_json/*.json"
                codec => "json"
        }
}

output {
    elasticsearch {
        hosts => [ "10.0.2.149" ]
        index => "l"
    }
}
```

**Comment by andrewvc** [comment]
The file input reads line by line while the `json` codec needs the whole JSON document.

You'll need to process the file first with something like `jq` to turn it into a single line, or better yet write a shell script to turn the whole directory into a single JSON file.

**Comment by naisanza** [comment]
@andrewvc oh wow. I wasn't expecting that 

I would have assumed the file input would take the path, then take each file, and read it with the json codec. 

This should be an improvement

**Comment by Tuurlijk** [comment]
@naisanza This is what you should use json_lines codec for: https://www.elastic.co/guide/en/logstash/5.2/plugins-codecs-json_lines.html
