### ISSUE TITLE
Logstash 2.4 fails with valid json when specifying an array

### ISSUE THREAD

**Issue by jb4x** [logstash-plugins/logstash-codec-json#32]
- Version: Logstash 2.4.1(not sure what plugin version is OOTB)
- Operating System: Mac, but doesn't matter
- Config File (if you have sensitive info, please remove it): n/a
- Sample Data: n/a
- Steps to Reproduce:

```
echo '[{"m":1},{"n":2}]' | bin/logstash -e 'input { stdin { codec => json } } output { stdout { codec => rubydebug { metadata => true } } }'

Settings: Default pipeline workers: 4
Pipeline main started
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Stdin codec=><LogStash::Codecs::JSON charset=>"UTF-8">>
  Error: can't convert String into Integer {:level=>:error}
Pipeline main has been shutdown
stopping pipeline {:id=>"main"}
```

**Comment by yaauie** [comment]
I'm not sure when this was fixed as Logstash 2.x is _long_ past its EOL, but modern Logstash 8.x will correctly handle the provided example to produce two events.
