### ISSUE TITLE
Drop message with field with only contains "."

### ISSUE THREAD

**Issue by genofire** [logstash-plugins/logstash-codec-json#41]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)
4. How was the Logstash Plugin installed

**JVM** (e.g. `java -version`):

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`)
2. JVM installation source (e.g. from the Operating System's package manager, from source, etc).
3. Value of the `JAVA_HOME` environment variable if set.

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**expected behavour**:
Fallback to plain text codecs and add Tag `_jsonparsefailure`

**Provide logs (if relevant)**:

```
field name cannot contain only dots
```

**Comment by jsvd** [comment]
The codec tries to parse the input it receives to JSON, and it if can't then the message is stored as-is and the _jsonparse failure tag is added, example:

```
❯ bin/logstash -e "input { generator { codec => json message => \",\" count => 1 }}"
{
       "message" => ",",
          "tags" => [
        [0] "_jsonparsefailure"
    ],
          "host" => "MacBook-Pro.Home",
      "sequence" => 0,
      "@version" => "1",
    "@timestamp" => 2022-04-20T12:48:37.041Z
}
```

If you don't want those events you can drop all events with a given tag with:

```
if "_jsonparsefailure" in [tags] { drop { } }
```

Otherwise I don't see a bug in the described report. so I'm closing the issue.

**Comment by genofire** [comment]
That is the descripted **expected behaviour** which i would like to get.

**Comment by jsvd** [comment]
is there an issue with using the drop filter in they way I described?
defaulting to dropping data on the codec itself would be a breaking change and other people have use cases where failed parsed messages are stored in a different place for later analysis and indexing.
Tagging on error is the same approach we have in many codecs and filters: cef, date, grok, geoip, ruby, etc.
